### ISSUE TITLE
Migrate aws-account-operator to Go 1.18

### ISSUE THREAD

**Issue by bergmannf** [openshift/aws-account-operator#697]
Right now the `boilerplate` ci checks only work, when running Go 1.17.

We should think about migrating to Go 1.18 - as this is the current major version (and also the default on Fedora 36).

As part of that, the boilerplate needs to be updated as well, as `golangci-lint` used by it currently is version 1.30.0, which is not compatible with Go 1.18:

`ERRO Running error: buildir: failed to load package goarch: could not load export data: cannot import "internal/goarch" (unknown iexport format version 2), export data is newer version - update tool`

**Comment by fahlmant** [comment]
@bergmannf Please use OSD jira cards to track these requests.

**Comment by bergmannf** [comment]
Migrated this to OSD-11591
